from __future__ import annotations

from app.production_schemas import (
    BuildEngineEditorResponse,
    EngineEditorChoice,
    EngineEditorFieldDefinition,
    EngineEditorGroup,
)
from app.schemas import BuildState
from app.services.catalog_seed import CAM_PROFILES
from app.services.seed_repository import get_repository
from app.services.simulation_dataset_service import default_engine_spec_updates


def _select_choices(items: list[tuple[str, str]]) -> list[EngineEditorChoice]:
    return [EngineEditorChoice(value=value, label=label) for value, label in items]


def _field(
    *,
    field_id: str,
    label: str,
    input_kind: str,
    current_value,
    default_value,
    short_help: str,
    why_it_matters: str,
    affects: list[str],
    tradeoffs: list[str],
    source: str,
    unit: str | None = None,
    min_value: float | None = None,
    max_value: float | None = None,
    step: float | None = None,
    warning_thresholds: dict[str, object] | None = None,
    choices: list[EngineEditorChoice] | None = None,
) -> EngineEditorFieldDefinition:
    return EngineEditorFieldDefinition(
        field_id=field_id,
        label=label,
        input_kind=input_kind,  # type: ignore[arg-type]
        unit=unit,
        current_value=current_value,
        default_value=default_value,
        min=min_value,
        max=max_value,
        step=step,
        short_help=short_help,
        why_it_matters=why_it_matters,
        affects=affects,
        tradeoffs=tradeoffs,
        warning_thresholds=warning_thresholds or {},
        source=source,
        choices=choices or [],
    )


def build_engine_editor_response(build: BuildState) -> BuildEngineEditorResponse:
    repository = get_repository()
    source_mode = "licensed" if repository.get_vehicle_record(build.vehicle.trim_id) is not None else "seed"
    default_engine = repository.get_default_engine_config(build.vehicle.trim_id)
    default_drivetrain = repository.get_default_drivetrain_config(build.vehicle.trim_id)
    engine_family = repository.get_engine_family(build.engine_build_spec.engine_family_id)
    default_advanced = default_engine_spec_updates(engine_family=engine_family)

    field_sources = {
        "engine": "imported_engine_config" if source_mode == "licensed" else "seed_engine_config",
        "calibration": "simulation_calibration_profile",
        "drivetrain": "imported_drivetrain_config" if source_mode == "licensed" else "seed_drivetrain_config",
    }

    groups: list[EngineEditorGroup] = [
        EngineEditorGroup(
            group_id="bottom_end",
            label="Bottom End",
            description="Core displacement and piston-speed inputs that shape torque, revs, and stress.",
            fields=[
                _field(
                    field_id="bore_mm",
                    label="Bore",
                    input_kind="number",
                    unit="mm",
                    current_value=build.engine_build_spec.bore_mm,
                    default_value=default_engine.bore_mm,
                    min_value=80.0,
                    max_value=102.0,
                    step=0.1,
                    short_help="Cylinder diameter. Larger bores add valve area and displacement.",
                    why_it_matters="Bore changes displacement, airflow potential, and piston-speed tradeoffs with stroke.",
                    affects=["displacement", "airflow", "peak_hp"],
                    tradeoffs=["Large bores can hurt wall stability and combustion quality if pushed too far."],
                    warning_thresholds={"soft_max": 98.0},
                    source=field_sources["engine"],
                ),
                _field(
                    field_id="stroke_mm",
                    label="Stroke",
                    input_kind="number",
                    unit="mm",
                    current_value=build.engine_build_spec.stroke_mm,
                    default_value=default_engine.stroke_mm,
                    min_value=72.0,
                    max_value=98.0,
                    step=0.1,
                    short_help="Crank throw. Longer stroke adds leverage and displacement.",
                    why_it_matters="Stroke raises torque potential but also increases mean piston speed at a given RPM.",
                    affects=["displacement", "torque", "piston_speed"],
                    tradeoffs=["Long-stroke setups build torque earlier but resist very high redlines."],
                    warning_thresholds={"soft_max": 92.0},
                    source=field_sources["engine"],
                ),
                _field(
                    field_id="rod_length_mm",
                    label="Rod Length",
                    input_kind="number",
                    unit="mm",
                    current_value=build.engine_build_spec.rod_length_mm,
                    default_value=default_advanced["rod_length_mm"],
                    min_value=110.0,
                    max_value=155.0,
                    step=0.1,
                    short_help="Center-to-center rod length used in the rod/stroke ratio.",
                    why_it_matters="Rod ratio shifts dwell time, piston acceleration, and high-RPM stability.",
                    affects=["rod_ratio", "midrange_shape", "stress"],
                    tradeoffs=["Short rods usually sharpen low-end response but raise side loading and stress."],
                    warning_thresholds={"soft_min": 118.0, "soft_max": 142.0},
                    source=field_sources["calibration"],
                ),
                _field(
                    field_id="compression_ratio",
                    label="Compression Ratio",
                    input_kind="number",
                    unit=":1",
                    current_value=build.engine_build_spec.compression_ratio,
                    default_value=default_engine.compression_ratio,
                    min_value=8.0,
                    max_value=14.5,
                    step=0.1,
                    short_help="Static compression before ignition.",
                    why_it_matters="Higher compression improves efficiency and response, but it pushes knock sensitivity.",
                    affects=["thermal_efficiency", "torque", "knock_margin"],
                    tradeoffs=["High compression wants better fuel, charge cooling, and careful ignition timing."],
                    warning_thresholds={"soft_max": 13.2},
                    source=field_sources["engine"],
                ),
                _field(
                    field_id="rev_limit_rpm",
                    label="Rev Limit",
                    input_kind="number",
                    unit="rpm",
                    current_value=build.engine_build_spec.rev_limit_rpm,
                    default_value=default_engine.rev_limit_rpm,
                    min_value=6200.0,
                    max_value=9000.0,
                    step=50.0,
                    short_help="Hard engine speed cap used for the dyno curve and shift targets.",
                    why_it_matters="Rev limit changes usable powerband width and piston-speed stress at the top of the run.",
                    affects=["usable_band", "shift_points", "piston_speed"],
                    tradeoffs=["More RPM can improve peak power if the head can support it, but durability drops quickly."],
                    warning_thresholds={"soft_max": 7800.0},
                    source=field_sources["engine"],
                ),
            ],
        ),
        EngineEditorGroup(
            group_id="head_and_cams",
            label="Head and Cams",
            description="Valve event and flow controls that reshape where the engine breathes best.",
            fields=[
                _field(
                    field_id="head_flow_stage",
                    label="Head Flow Stage",
                    input_kind="select",
                    current_value=build.engine_build_spec.valve_train.head_flow_stage,
                    default_value=default_engine.valve_train.head_flow_stage,
                    short_help="How far the head and ports are developed beyond stock.",
                    why_it_matters="Head flow lifts the VE ceiling, especially once RPM rises and airflow demand spikes.",
                    affects=["volumetric_efficiency", "peak_hp", "high_rpm_pull"],
                    tradeoffs=["Aggressive head work can soften low-speed velocity and drivability."],
                    source=field_sources["engine"],
                    choices=_select_choices([("stock", "Stock"), ("street", "Street"), ("race", "Race")]),
                ),
                _field(
                    field_id="cam_profile_id",
                    label="Cam Profile",
                    input_kind="select",
                    current_value=build.engine_build_spec.cam_profile.profile_id,
                    default_value=default_engine.cam_profile.profile_id,
                    short_help="Named cam behavior preset used as the broad valve-event personality.",
                    why_it_matters="Cam profile moves torque around the curve before the detailed duration and lift values fine-tune it.",
                    affects=["low_end", "top_end", "torque_shape"],
                    tradeoffs=["Big cams usually add top-end but reduce idle quality and low-speed response."],
                    source=field_sources["engine"],
                    choices=_select_choices([(profile.profile_id, profile.label) for profile in CAM_PROFILES.values()]),
                ),
                _field(
                    field_id="intake_cam_duration_deg",
                    label="Intake Duration",
                    input_kind="number",
                    unit="deg",
                    current_value=build.engine_build_spec.intake_cam_duration_deg,
                    default_value=default_advanced["intake_cam_duration_deg"],
                    min_value=210.0,
                    max_value=300.0,
                    step=1.0,
                    short_help="Approximate intake valve duration at the chosen checking height.",
                    why_it_matters="Longer intake duration usually helps high-RPM filling while trading away low-speed cylinder pressure.",
                    affects=["ve_curve", "peak_hp", "low_end_response"],
                    tradeoffs=["Duration that is too long can flatten midrange and make the engine lazier below boost."],
                    warning_thresholds={"soft_max": 272.0},
                    source=field_sources["calibration"],
                ),
                _field(
                    field_id="exhaust_cam_duration_deg",
                    label="Exhaust Duration",
                    input_kind="number",
                    unit="deg",
                    current_value=build.engine_build_spec.exhaust_cam_duration_deg,
                    default_value=default_advanced["exhaust_cam_duration_deg"],
                    min_value=208.0,
                    max_value=296.0,
                    step=1.0,
                    short_help="Approximate exhaust valve duration at the chosen checking height.",
                    why_it_matters="Exhaust duration controls blowdown and how hard the engine works against backpressure.",
                    affects=["high_rpm_flow", "backpressure_tolerance", "boost_response"],
                    tradeoffs=["Too much exhaust duration can erode midrange torque and spool behavior."],
                    warning_thresholds={"soft_max": 270.0},
                    source=field_sources["calibration"],
                ),
                _field(
                    field_id="intake_lift_mm",
                    label="Intake Lift",
                    input_kind="number",
                    unit="mm",
                    current_value=build.engine_build_spec.intake_lift_mm,
                    default_value=default_advanced["intake_lift_mm"],
                    min_value=7.0,
                    max_value=14.0,
                    step=0.1,
                    short_help="Maximum intake valve lift.",
                    why_it_matters="Lift expands curtain area and helps the head use its flow capacity.",
                    affects=["airflow", "ve_peak", "top_end"],
                    tradeoffs=["Very high lift demands spring control and valvetrain stability."],
                    warning_thresholds={"soft_max": 12.0},
                    source=field_sources["calibration"],
                ),
                _field(
                    field_id="exhaust_lift_mm",
                    label="Exhaust Lift",
                    input_kind="number",
                    unit="mm",
                    current_value=build.engine_build_spec.exhaust_lift_mm,
                    default_value=default_advanced["exhaust_lift_mm"],
                    min_value=7.0,
                    max_value=14.0,
                    step=0.1,
                    short_help="Maximum exhaust valve lift.",
                    why_it_matters="Exhaust lift helps clear the cylinder and fight turbine or system backpressure.",
                    affects=["evacuation", "backpressure", "top_end"],
                    tradeoffs=["Too much lift raises valvetrain demand without always adding flow."],
                    warning_thresholds={"soft_max": 11.8},
                    source=field_sources["calibration"],
                ),
                _field(
                    field_id="lobe_separation_deg",
                    label="Lobe Separation",
                    input_kind="number",
                    unit="deg",
                    current_value=build.engine_build_spec.lobe_separation_deg,
                    default_value=default_advanced["lobe_separation_deg"],
                    min_value=104.0,
                    max_value=118.0,
                    step=0.5,
                    short_help="Angle between intake and exhaust lobe centerlines.",
                    why_it_matters="Lobe separation changes overlap, spool behavior, idle quality, and midrange character.",
                    affects=["overlap", "spool", "idle_quality"],
                    tradeoffs=["Tighter LSA sharpens torque and spool but often raises overlap sensitivity and heat."],
                    warning_thresholds={"soft_min": 107.0, "soft_max": 115.0},
                    source=field_sources["calibration"],
                ),
            ],
        ),
        EngineEditorGroup(
            group_id="induction_and_boost",
            label="Induction and Boost",
            description="Pressure-ratio and charge-temperature controls for naturally aspirated or boosted operation.",
            fields=[
                _field(
                    field_id="induction_type",
                    label="Induction Type",
                    input_kind="select",
                    current_value=build.engine_build_spec.induction.type,
                    default_value=default_engine.induction.type,
                    short_help="Chooses whether the model treats the engine as NA, turbocharged, or supercharged.",
                    why_it_matters="Induction type changes pressure ratio, charge heating, and where torque arrives in the curve.",
                    affects=["pressure_ratio", "boost_response", "charge_temp"],
                    tradeoffs=["Boost adds airflow fast, but it also raises temperature and driveline load."],
                    source=field_sources["engine"],
                    choices=_select_choices([("na", "Naturally Aspirated"), ("turbo", "Turbo"), ("supercharger", "Supercharger")]),
                ),
                _field(
                    field_id="boost_psi",
                    label="Boost Target",
                    input_kind="number",
                    unit="psi",
                    current_value=build.engine_build_spec.induction.boost_psi,
                    default_value=default_engine.induction.boost_psi,
                    min_value=0.0,
                    max_value=32.0,
                    step=0.5,
                    short_help="Requested manifold boost pressure above ambient.",
                    why_it_matters="Boost raises air mass and torque, but it also pushes charge temperature and knock risk.",
                    affects=["air_mass", "torque", "charge_temp"],
                    tradeoffs=["More boost only helps until fuel, knock, or cooling becomes the real limiter."],
                    warning_thresholds={"soft_max": 18.0},
                    source=field_sources["engine"],
                ),
                _field(
                    field_id="compressor_efficiency",
                    label="Compressor Efficiency",
                    input_kind="number",
                    unit="ratio",
                    current_value=build.engine_build_spec.compressor_efficiency,
                    default_value=default_advanced["compressor_efficiency"],
                    min_value=0.5,
                    max_value=0.85,
                    step=0.01,
                    short_help="How efficiently the compressor adds pressure instead of heat.",
                    why_it_matters="A better compressor gives more dense charge air at the same boost target.",
                    affects=["charge_temp", "air_density", "thermal_margin"],
                    tradeoffs=["Low efficiency makes boost feel expensive because heat rises faster than airflow."],
                    warning_thresholds={"soft_min": 0.62},
                    source=field_sources["calibration"],
                ),
                _field(
                    field_id="intercooler_effectiveness",
                    label="Intercooler Effectiveness",
                    input_kind="number",
                    unit="ratio",
                    current_value=build.engine_build_spec.intercooler_effectiveness,
                    default_value=default_advanced["intercooler_effectiveness"],
                    min_value=0.0,
                    max_value=0.95,
                    step=0.01,
                    short_help="How much of the compressor heat the intercooler removes before the manifold.",
                    why_it_matters="Intercooler effectiveness drives charge temperature, knock headroom, and repeated-pull consistency.",
                    affects=["charge_temp", "knock_margin", "thermal_headroom"],
                    tradeoffs=["Weak intercooling forces timing and power derates long before boost runs out."],
                    warning_thresholds={"soft_min": 0.65},
                    source=field_sources["calibration"],
                ),
            ],
        ),
    ]

    groups.extend(
        [
            EngineEditorGroup(
                group_id="fuel_and_ignition",
                label="Fuel and Ignition",
                description="How the engine is fueled, how rich it runs, and how hard spark timing leans on knock margin.",
                fields=[
                    _field(
                        field_id="fuel_type",
                        label="Fuel",
                        input_kind="select",
                        current_value=build.engine_build_spec.fuel.fuel_type,
                        default_value=default_engine.fuel.fuel_type,
                        short_help="Fuel blend used for stoich AFR, knock support, and best-power lambda.",
                        why_it_matters="Fuel changes knock margin and how much mass flow is needed to support a target power level.",
                        affects=["knock_margin", "fuel_flow", "combustion_efficiency"],
                        tradeoffs=["High-knock-resistance fuels support power, but they change fueling demand substantially."],
                        source=field_sources["engine"],
                        choices=_select_choices([("91_octane", "91 Octane"), ("93_octane", "93 Octane"), ("e85", "E85")]),
                    ),
                    _field(
                        field_id="injector_scale",
                        label="Injector Scale",
                        input_kind="select",
                        current_value=build.engine_build_spec.fuel.injector_scale,
                        default_value=default_engine.fuel.injector_scale,
                        short_help="Relative injector headroom available at peak fuel demand.",
                        why_it_matters="Injectors cap how much fuel mass the engine can sustain before the model imposes a fuel-limit derate.",
                        affects=["fuel_limit", "peak_power", "safety_margin"],
                        tradeoffs=["Undersized injectors force lean-out or power derate right when airflow is highest."],
                        source=field_sources["engine"],
                        choices=_select_choices([("stock", "Stock"), ("upgrade", "Upgrade"), ("high_flow", "High Flow")]),
                    ),
                    _field(
                        field_id="pump_scale",
                        label="Pump Scale",
                        input_kind="select",
                        current_value=build.engine_build_spec.fuel.pump_scale,
                        default_value=default_engine.fuel.pump_scale,
                        short_help="Relative fuel pump delivery capacity.",
                        why_it_matters="Pump capacity works with injector sizing to decide whether the engine can hold commanded lambda at load.",
                        affects=["fuel_limit", "stability", "high_load_power"],
                        tradeoffs=["Pump headroom is easy to ignore until a boosted combo starts leaning out at the top end."],
                        source=field_sources["engine"],
                        choices=_select_choices([("stock", "Stock"), ("upgrade", "Upgrade"), ("high_flow", "High Flow")]),
                    ),
                    _field(
                        field_id="target_lambda",
                        label="Target Lambda",
                        input_kind="number",
                        unit="lambda",
                        current_value=build.engine_build_spec.target_lambda,
                        default_value=default_advanced["target_lambda"],
                        min_value=0.7,
                        max_value=1.05,
                        step=0.01,
                        short_help="Wide-open-throttle richness target relative to stoichiometric.",
                        why_it_matters="Lambda trades combustion stability, exhaust heat, and knock margin against raw efficiency.",
                        affects=["combustion_efficiency", "egt", "knock_margin"],
                        tradeoffs=["Richer targets cool the chamber, while leaner targets gain efficiency but raise heat and risk."],
                        warning_thresholds={"soft_min": 0.78, "soft_max": 0.95},
                        source=field_sources["calibration"],
                    ),
                    _field(
                        field_id="ignition_advance_bias_deg",
                        label="Ignition Advance Bias",
                        input_kind="number",
                        unit="deg",
                        current_value=build.engine_build_spec.ignition_advance_bias_deg,
                        default_value=default_advanced["ignition_advance_bias_deg"],
                        min_value=-8.0,
                        max_value=8.0,
                        step=0.25,
                        short_help="Global spark timing bias relative to the calibrated base map.",
                        why_it_matters="Advance changes burn phasing and torque, but it is one of the fastest ways to hit a knock wall.",
                        affects=["torque", "knock_limit", "charge_heat"],
                        tradeoffs=["Aggressive timing can add sharp response until fuel and charge temp stop cooperating."],
                        warning_thresholds={"soft_max": 3.0},
                        source=field_sources["calibration"],
                    ),
                    _field(
                        field_id="tune_bias",
                        label="Tune Bias",
                        input_kind="select",
                        current_value=build.engine_build_spec.tune_bias,
                        default_value=default_engine.tune_bias,
                        short_help="High-level tune posture between comfort, balance, and aggression.",
                        why_it_matters="Tune bias adjusts the model’s target for drivability versus outright power and heat.",
                        affects=["timing", "lambda_target", "response"],
                        tradeoffs=["Aggressive tuning finds power faster, but it spends more knock and thermal budget."],
                        source=field_sources["engine"],
                        choices=_select_choices([("comfort", "Comfort"), ("balanced", "Balanced"), ("aggressive", "Aggressive")]),
                    ),
                ],
            ),
            EngineEditorGroup(
                group_id="exhaust",
                label="Exhaust",
                description="How easily the engine can clear the cylinder and how much pressure it has to work against.",
                fields=[
                    _field(
                        field_id="exhaust_style",
                        label="Exhaust Style",
                        input_kind="select",
                        current_value=build.engine_build_spec.exhaust.exhaust_style,
                        default_value=default_engine.exhaust.exhaust_style,
                        short_help="Overall exhaust architecture feeding the model’s backpressure assumptions.",
                        why_it_matters="Exhaust layout changes how quickly the engine empties the cylinder and how much heat stays in the system.",
                        affects=["backpressure", "spool", "peak_hp"],
                        tradeoffs=["Freer exhausts usually add top-end power but increase noise and can soften low-speed torque."],
                        source=field_sources["engine"],
                        choices=_select_choices([("stock", "Stock"), ("catback", "Cat-back"), ("turbo_back", "Turbo-back"), ("equal_length", "Equal Length")]),
                    ),
                    _field(
                        field_id="exhaust_backpressure_factor",
                        label="Backpressure Factor",
                        input_kind="number",
                        unit="ratio",
                        current_value=build.engine_build_spec.exhaust_backpressure_factor,
                        default_value=default_advanced["exhaust_backpressure_factor"],
                        min_value=0.75,
                        max_value=1.35,
                        step=0.01,
                        short_help="Relative exhaust restriction multiplier used in the pumping-loss model.",
                        why_it_matters="Backpressure directly adds pumping work and can flatten power once airflow climbs.",
                        affects=["pumping_loss", "egt", "high_rpm_flow"],
                        tradeoffs=["Low restriction improves breathing, but real systems often trade emissions, noise, and packaging to get there."],
                        warning_thresholds={"soft_max": 1.12},
                        source=field_sources["calibration"],
                    ),
                ],
            ),
            EngineEditorGroup(
                group_id="cooling_and_ambient",
                label="Cooling and Ambient",
                description="Environmental conditions and cooling-system strength that shape derate behavior.",
                fields=[
                    _field(
                        field_id="radiator_effectiveness",
                        label="Radiator Effectiveness",
                        input_kind="number",
                        unit="ratio",
                        current_value=build.engine_build_spec.radiator_effectiveness,
                        default_value=default_advanced["radiator_effectiveness"],
                        min_value=0.55,
                        max_value=1.2,
                        step=0.01,
                        short_help="Relative cooling-system effectiveness against the family’s baseline heat rejection profile.",
                        why_it_matters="Radiator effectiveness decides how much peak-load heat the engine can reject before power derates.",
                        affects=["cooling_rejection", "thermal_headroom", "derate_risk"],
                        tradeoffs=["Cooling upgrades help repeatability, but they do not fix charge-temp or fuel-limit issues by themselves."],
                        warning_thresholds={"soft_min": 0.72},
                        source=field_sources["calibration"],
                    ),
                    _field(
                        field_id="ambient_temp_c",
                        label="Ambient Temperature",
                        input_kind="number",
                        unit="deg C",
                        current_value=build.engine_build_spec.ambient_temp_c,
                        default_value=default_advanced["ambient_temp_c"],
                        min_value=-15.0,
                        max_value=45.0,
                        step=1.0,
                        short_help="Outside air temperature used for density, compressor outlet heat, and cooling rejection.",
                        why_it_matters="Hot ambient air hurts density and cooling at the same time, so it can cost both power and repeatability.",
                        affects=["air_density", "charge_temp", "thermal_headroom"],
                        tradeoffs=["Cold air helps power, while hot weather exposes the weakest part of the cooling and knock budget."],
                        warning_thresholds={"soft_max": 32.0},
                        source="environment_assumption",
                    ),
                    _field(
                        field_id="altitude_m",
                        label="Altitude",
                        input_kind="number",
                        unit="m",
                        current_value=build.engine_build_spec.altitude_m,
                        default_value=default_advanced["altitude_m"],
                        min_value=0.0,
                        max_value=3500.0,
                        step=50.0,
                        short_help="Elevation above sea level used for ambient pressure and density correction.",
                        why_it_matters="Altitude reduces ambient pressure, so NA engines lose airflow and boosted engines work harder for the same manifold pressure.",
                        affects=["ambient_pressure", "air_mass", "compressor_work"],
                        tradeoffs=["High elevation can be recovered with boost, but that recovery usually costs heat and turbo effort."],
                        warning_thresholds={"soft_max": 1800.0},
                        source="environment_assumption",
                    ),
                ],
            ),
        ]
    )

    drivetrain_fields = [
        _field(
            field_id="final_drive_ratio",
            label="Final Drive",
            input_kind="number",
            unit="ratio",
            current_value=build.drivetrain_config.final_drive_ratio,
            default_value=default_drivetrain.final_drive_ratio,
            min_value=3.1,
            max_value=5.2,
            step=0.01,
            short_help="Final reduction after the gearbox.",
            why_it_matters="Final drive shifts every gear shorter or longer, so it changes launch feel, in-gear acceleration, and top-speed pull.",
            affects=["wheel_torque", "road_speed", "acceleration"],
            tradeoffs=["Shorter final drives feel faster but force more shifts and can cost top-end speed."],
            warning_thresholds={"soft_max": 4.6},
            source=field_sources["drivetrain"],
        ),
        _field(
            field_id="driveline_loss_factor",
            label="Driveline Loss",
            input_kind="number",
            unit="ratio",
            current_value=build.drivetrain_config.driveline_loss_factor,
            default_value=default_drivetrain.driveline_loss_factor,
            min_value=0.08,
            max_value=0.25,
            step=0.005,
            short_help="Fraction of engine output lost between the crank and the tire contact patch.",
            why_it_matters="This is why identical engine dynos can deliver different wheel force through different drivetrains.",
            affects=["wheel_output", "0_60", "top_speed"],
            tradeoffs=["Automatic or heavy driveline paths often absorb more power but can still improve consistency."],
            warning_thresholds={"soft_max": 0.18},
            source=field_sources["drivetrain"],
        ),
        _field(
            field_id="shift_latency_ms",
            label="Shift Latency",
            input_kind="number",
            unit="ms",
            current_value=build.drivetrain_config.shift_latency_ms,
            default_value=default_drivetrain.shift_latency_ms,
            min_value=80.0,
            max_value=450.0,
            step=5.0,
            short_help="How long full-throttle upshifts interrupt acceleration.",
            why_it_matters="Shift time shapes real acceleration much more than steady-state dyno numbers suggest.",
            affects=["acceleration", "quarter_mile", "driveability"],
            tradeoffs=["Short shift times improve ETs, but very sharp shifts can feel harsh or unrealistic."],
            warning_thresholds={"soft_max": 260.0},
            source=field_sources["drivetrain"],
        ),
        _field(
            field_id="differential_bias",
            label="Differential Bias",
            input_kind="select",
            current_value=build.drivetrain_config.differential_bias,
            default_value=default_drivetrain.differential_bias,
            short_help="Differential behavior used for launch traction and scenario heuristics.",
            why_it_matters="Diff bias changes how much of the engine’s torque the rear axle can actually use in transient conditions.",
            affects=["launch_traction", "corner_exit", "daily_behavior"],
            tradeoffs=["Aggressive lockup improves exits and launches but can make low-speed behavior harsher."],
            source=field_sources["drivetrain"],
            choices=_select_choices([("street_lsd", "Street LSD"), ("track_lsd", "Track LSD"), ("open", "Open"), ("torsen", "Torsen")]),
        ),
    ]

    for index, ratio in enumerate(build.drivetrain_config.gear_ratios, start=1):
        default_ratio = default_drivetrain.gear_ratios[index - 1] if index - 1 < len(default_drivetrain.gear_ratios) else ratio
        drivetrain_fields.append(
            _field(
                field_id=f"gear_ratio_{index}",
                label=f"Gear {index}",
                input_kind="number",
                unit="ratio",
                current_value=ratio,
                default_value=default_ratio,
                min_value=0.45,
                max_value=4.5,
                step=0.001,
                short_help=f"Ratio for gear {index}. Higher values multiply torque more strongly.",
                why_it_matters="Individual gear spacing decides how closely the engine stays near the strongest part of the curve after each shift.",
                affects=["wheel_force", "shift_drop", "speed_in_gear"],
                tradeoffs=["Tighter spacing keeps the engine in its powerband, but wide spacing can reduce shift count and noise."],
                warning_thresholds={"soft_min": 0.6 if index > 4 else 0.9},
                source=field_sources["drivetrain"],
            )
        )

    groups.append(
        EngineEditorGroup(
            group_id="drivetrain",
            label="Drivetrain",
            description="Torque delivery, wheel-force losses, and gear spacing for acceleration estimates.",
            fields=drivetrain_fields,
        )
    )

    return BuildEngineEditorResponse(
        build_id=build.build_id,
        build_hash=build.computation.build_hash,
        source_mode=source_mode,  # type: ignore[arg-type]
        groups=groups,
    )
